global:
  scrape_interval: 5s  # Adjust based on needs

scrape_configs:
  - job_name: "node_app"
    metrics_path: "/api/v1/metrics"  # Ensure your app exposes this endpoint
    static_configs:
      - targets: ["host.docker.internal:5000"]  # Works on Windows/macOS
